// Generated by diesel_ext
use chrono::offset::Utc;
use chrono::DateTime;
use serde::{Deserialize, Serialize};

#[derive(Deserialize, Serialize, Debug, Clone)]
pub struct Measurement {
    pub pi_id: String,
    pub measurement_time: DateTime<Utc>,
    pub temp1: f32,
    pub temp2: f32,
    pub temp3: f32,
    pub temp4: f32,
    pub bme_temp1: f32,
    pub bme_temp2: f32,
    pub pressure1: f32,
    pub pressure2: f32,
    pub rh1: f32,
    pub rh2: f32,
    pub image_data: Vec<f32>,
}
